config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root to: "home#index"

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :user

  validates :content, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < GenericModelsController
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  attr_reader :post
  
  def index
    redirect_to "/posts/#{post.id}"
  end


  def create
    @comment = Comment.create! content: params[:comment][:content], user: current_user, post: post
    broadcast_comment
    redirect_to "/posts/#{post.id}"
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def destroy
    comment = Comment.find_by(id: params[:id])
    comment.destroy
    redirect_to "/posts/#{post.id}"
  end

  private
  def set_post
    puts params[:post_id]
    post_id = params[:post_id] || (params[:comment].present? ? params[:comment][:post_id] : nil)
    raise 'Post ID is mandatory' if post_id.nil?
    @post = Post.find_by(:id => post_id)
  end

  def broadcast_comment
    ActionCable.server.broadcast('comments',
        message: @comment.content,
        email: @comment.user.email,
        post_id: post.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  attr_reader :post

  def index
    Rails.logger.debug "current_user #{current_user}"
    @posts = Post.all
  end

  def create
    @post = Post.create! content: params[:post][:content], title: params[:post][:content], user: current_user
    notify_new_post
    redirect_to '/posts'
  end

  def new
    @post = Post.new
  end


  def show
    Rails.logger.debug "current_user #{current_user.inspect}"
    set_post
    @show_delete = (@post.user.email == current_user.email)
  end

  def destroy
    set_post
    post.destroy
    redirect_to '/posts'
  end


  private
  def set_post
    post_id = params[:id]
    raise 'Post ID is mandatory' if post_id.nil?
    @post = Post.includes(:comments,:user).find_by(id: post_id)
    raise 'Post not found error' unless @post.present? #handle gracefully
  end

  def notify_new_post
        ActionCable.server.broadcast 'notifications',
        title: @post.title,
        email: @post.user.email,
        content: @post.content,
        post_id: @post.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comments.html.erb
<div class='container'>
  <h4>Comments</h4>

  <ul>
    <% @post.comments.includes(:user).each do |comment| %>
      <li>
        <p>
        <%= comment.user.email %>
        <span><small>&nbsp;says:&nbsp;</small> <%= comment.content %> </span>
        <% if current_user.email == comment.user.email %>
          <span><%= link_to "Delete", post_comment_path(@post, comment), :method => :delete %></span>
        <% end %>
        </p>
      </li>
    <% end %>
  </ul>
</div>


<style type="text/css">  
  ul.list-group:after {
  clear: both;
  display: block;
  content: "";
}

.list-group-item {
    float: left;
    margin: 0px;
    padding: 3% 0px;
}
</style>  

app/views/comments/_new.html.erb
<div class="container space-above">
      <%= form_for [post, Comment.new] do |f| %>
            <p>
                  <%= f.text_area :content, placeholder: "Commenting as #{current_user.email}", class: 'md-textarea form-control', rows:"2" %>
                  <%= f.hidden_field :post_id, :value => @post.id %>
            </p>
            </div>
            <p>
                  <%= f.submit 'Save',  class:"btn btn-primary"%>
            </p>
      <% end %>

</div>

<style type="text/css">
      .space_above{
            padding-top: 40px;
      }
</style>

app/views/home/index.html.erb
<div class='container'>
  <% if user_signed_in? %>


  <h3>Welcome!</h3>
  <%= link_to 'Create Post', new_post_path %>
  <%= link_to 'View Posts', posts_path %> 


  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockr</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'util/toast' %>
<div class='container'>
  <div>
    <h1>Posts</h1>
    <h2 class='right-align'><%= link_to 'Create Post', new_post_path %>  </h2>
  </div>
  <section>
    <ul class="list-unstyled">
      <% @posts.each do |post| %>
        <li class=".list-group-item">
          <%= link_to post.content, post %>  
        </li>
        <hr>
      <% end %>
    </ul>
  </section>
</div>



<style type="text/css">  
  ul.list-group:after {
  clear: both;
  display: block;
  content: "";
}

.list-group-item {
    float: left;
    margin: 0px;
    padding: 3% 0px;
}

a {
  display: block;
  padding: 20px;
  text-decoration: none !important;
  font-size: 20px;
  /*border: 1px solid;*/
}


</style>  

app/views/posts/new.html.erb
<%= render 'util/toast' %>
<div class="container new_post">
  <!-- Content here -->
<%= form_for @post, :html => {:class => "form-group"} do |f| %>
      <%= f.text_field :title , class:"form-control bottom-spacing", placeholder: "Stock Recommendation Title" %>
      <%= f.text_area :content, placeholder: "Description", class: 'md-textarea form-control bottom-spacing', rows:"2" %>
      <%= f.submit 'Create Post', class:"btn btn-primary" %>
<% end %>
</div>

<style type="text/css">
      .new_post{
            margin: 5%;
      }
      .bottom-spacing {
                  margin-bottom: 3%;
      }
</style>

app/views/posts/show.html.erb
<%= render 'util/toast' %>
<div class='container'>

  <div id="single–post" data-channel="posts" data-post-id="<%= @post.id %>">
    <p>
      <h2> <%= @post.user.email %> 's post </h2>
      <% if @show_delete %>
        <span><%= link_to "Delete", post_path, :method => :delete %></span>
      <% end %>
    </p>
    <hr>
    <em>Title:&nbsp<%= @post.title %> </br></br>
        Description:&nbsp;<%= @post.content %> 
    </h3>
  </div>
  <section id="comments" data-channel="comments" >
    <%= render 'comments/comments', post: @message %>
  </section>
  <%= render 'comments/new', post: @post %>

</div>

app/views/util/_toast.html.erb
<div class="toast right-align" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <strong></strong>
  </div>
  <div class="toast-body">
    <a href=""></a>
  </div>
</div>
<style type="text/css">
  .right-align {
    text-align: right;
    margin: 1%;
  }
</style>